import java.util.Random;
import java.util.Scanner;

public class NumberGame {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Random rnd = new Random();
        String playAgain;

        do {
            int a = rnd.nextInt(100);
            System.out.println("                    NUMBER GAME");
            System.out.println("Guess The Number:  ");
            System.out.println("You have 3 chances. Choose between 1 to 100:");

            for (int i = 0; i < 3; i++) {
                int Guess = scanner.nextInt();
                if (Guess > a) {
                    System.out.println("TOO HIGH");
                } else if (Guess < a) {
                    System.out.println("TOO LOW");
                } else {
                    System.out.println("YOU WON. Guess is correct ");
                    break;
                }
                if (i == 2 && a != Guess) {
                    System.out.println("**YOU LOST**");
                }
            }
                 System.out.println("The number generated by the computer is: " + a);

            System.out.println("Do you want to play again? (yes/no)");
            playAgain = scanner.next();
        } while (playAgain.equalsIgnoreCase("yes"));

        scanner.close();
    }
}
